
CREATE TABLE USUARIO (
  ID INT NOT NULL,
  NOME VARCHAR(200) NOT NULL,
  SENHA VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID));

CREATE TABLE POST (
  ID INT NOT NULL,
  TITULO VARCHAR(200) NOT NULL,
  TEXTO TEXT NOT NULL,
  DATA DATETIME NULL,
  USUARIO_ID INT NOT NULL,
  PRIMARY KEY (ID),
  INDEX fk_POST_USUARIO_idx (USUARIO_ID ASC),
  CONSTRAINT fk_POST_USUARIO
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TRIGGER DATA_AUTOMATICA
ON POST
AFTER INSERT
AS BEGIN
	UPDATE POST
   SET DATA = GETDATE()
   FROM INSERTED i
   WHERE i.ID = POST.ID

END



CREATE TABLE CATEGORIA (
  ID INT NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID));


CREATE TABLE COMENTARIO (
  ID INT NOT NULL,
  TEXTO VARCHAR(200) NOT NULL,
  DATA DATETIME NOT NULL,
  POST_ID INT NOT NULL,
  USUARIO_ID INT NOT NULL,
  COMENTARIO_ID INT NOT NULL,
  PRIMARY KEY (ID),
  INDEX fk_COMENTARIO_POST1_idx (POST_ID ASC),
  INDEX fk_COMENTARIO_USUARIO1_idx (USUARIO_ID ASC),
  INDEX fk_COMENTARIO_COMENTARIO1_idx (COMENTARIO_ID ASC),
  CONSTRAINT fk_COMENTARIO_POST1
    FOREIGN KEY (POST_ID)
    REFERENCES POST (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_COMENTARIO_USUARIO1
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_COMENTARIO_COMENTARIO1
    FOREIGN KEY (COMENTARIO_ID)
    REFERENCES COMENTARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE CATEGORIA_POST (
  CATEGORIA_ID INT NOT NULL,
  POST_ID INT NOT NULL,
  INDEX fk_CATEGORIA_POST_CATEGORIA1_idx (CATEGORIA_ID ASC),
  INDEX fk_CATEGORIA_POST_POST1_idx (POST_ID ASC),
  CONSTRAINT fk_CATEGORIA_POST_CATEGORIA1
    FOREIGN KEY (CATEGORIA_ID)
    REFERENCES CATEGORIA (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_CATEGORIA_POST_POST1
    FOREIGN KEY (POST_ID)
    REFERENCES POST (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

